import {
  IOfflinePayment,
  IOnlinePayment,
  IPayment,
  IRefundPayment,
} from "@/types/payment";

export const PaymentsData: IPayment[] = [
  {
    no: 1,
    withdrawId: "WD001",
    withdrawMethod: "Bank Transfer",
    accountName: "John Doe",
    accountNumber: 1234567890,
    withdrawAmount: 1000,
    withdrawDay: "Monday",
    status: "Completed",
  },
  {
    no: 2,
    withdrawId: "WD002",
    withdrawMethod: "PayPal",
    accountName: "Jane Smith",
    accountNumber: 9876543210,
    withdrawAmount: 500,
    withdrawDay: "Tuesday",
    status: "Pending",
  },
  {
    no: 3,
    withdrawId: "WD003",
    withdrawMethod: "Bank Transfer",
    accountName: "Alice Johnson",
    accountNumber: 2468135790,
    withdrawAmount: 750,
    withdrawDay: "Wednesday",
    status: "Failed",
  },
  {
    no: 4,
    withdrawId: "WD004",
    withdrawMethod: "Cheque",
    accountName: "Michael Brown",
    accountNumber: 1357924680,
    withdrawAmount: 1200,
    withdrawDay: "Thursday",
    status: "Completed",
  },
  {
    no: 5,
    withdrawId: "WD005",
    withdrawMethod: "Bank Transfer",
    accountName: "Emily Davis",
    accountNumber: 3698521470,
    withdrawAmount: 850,
    withdrawDay: "Friday",
    status: "Pending",
  },
  {
    no: 6,
    withdrawId: "WD006",
    withdrawMethod: "PayPal",
    accountName: "Christopher Wilson",
    accountNumber: 9517534680,
    withdrawAmount: 600,
    withdrawDay: "Saturday",
    status: "Completed",
  },
  {
    no: 7,
    withdrawId: "WD007",
    withdrawMethod: "Cheque",
    accountName: "Sarah Martinez",
    accountNumber: 2587413690,
    withdrawAmount: 1100,
    withdrawDay: "Sunday",
    status: "Pending",
  },
  {
    no: 8,
    withdrawId: "WD008",
    withdrawMethod: "Bank Transfer",
    accountName: "David Rodriguez",
    accountNumber: 1234567890,
    withdrawAmount: 950,
    withdrawDay: "Monday",
    status: "Completed",
  },
  {
    no: 9,
    withdrawId: "WD009",
    withdrawMethod: "PayPal",
    accountName: "Linda Wilson",
    accountNumber: 9876543210,
    withdrawAmount: 700,
    withdrawDay: "Tuesday",
    status: "Failed",
  },
  {
    no: 10,
    withdrawId: "WD010",
    withdrawMethod: "Cheque",
    accountName: "Richard Lee",
    accountNumber: 2468135790,
    withdrawAmount: 1300,
    withdrawDay: "Wednesday",
    status: "Completed",
  },
];

export const OnlinePaymentData: IOnlinePayment[] = [
  {
    no: 1,
    paymentId: "PAY001",
    projectName: "Project A",
    paymentType: "Credit Card",
    accountName: "John Doe",
    accountNumber: "**** **** **** 1234",
    transactionId: "TRANS001",
    payMoney: 1000,
    paymentDay: "2024-04-19",
    status: "Success",
  },
  {
    no: 2,
    paymentId: "PAY002",
    projectName: "Project B",
    paymentType: "PayPal",
    accountName: "Jane Smith",
    accountNumber: "jane.smith@example.com",
    transactionId: "TRANS002",
    payMoney: 1500,
    paymentDay: "2024-04-20",
    status: "Success",
  },
  {
    no: 3,
    paymentId: "PAY003",
    projectName: "Project C",
    paymentType: "Bank Transfer",
    accountName: "Michael Johnson",
    accountNumber: "123456789",
    transactionId: "TRANS003",
    payMoney: 2000,
    paymentDay: "2024-04-21",
    status: "Pending",
  },
  {
    no: 4,
    paymentId: "PAY004",
    projectName: "Project D",
    paymentType: "Credit Card",
    accountName: "Emily Brown",
    accountNumber: "**** **** **** 5678",
    transactionId: "TRANS004",
    payMoney: 1200,
    paymentDay: "2024-04-22",
    status: "Success",
  },
  {
    no: 5,
    paymentId: "PAY005",
    projectName: "Project E",
    paymentType: "Bank Transfer",
    accountName: "Daniel Wilson",
    accountNumber: "987654321",
    transactionId: "TRANS005",
    payMoney: 1800,
    paymentDay: "2024-04-23",
    status: "Success",
  },
  {
    no: 6,
    paymentId: "PAY006",
    projectName: "Project F",
    paymentType: "Credit Card",
    accountName: "Olivia Taylor",
    accountNumber: "**** **** **** 9012",
    transactionId: "TRANS006",
    payMoney: 2500,
    paymentDay: "2024-04-24",
    status: "Pending",
  },
];

export const OfflinePaymentData: IOfflinePayment[] = [
  {
    no: 1,
    paymentId: "PAY123456789",
    projectName: "Project A",
    countryName: "USA",
    receiptPersonId: "USR987654321",
    checkNumber: "CHK123456",
    checkSecurityCode: "123",
    checkAmount: 1000,
    checkHolderName: "John Doe",
    paymentDay: "2024-04-19",
    status: "Pending",
  },
  {
    no: 2,
    paymentId: "PAY987654321",
    projectName: "Project B",
    countryName: "Canada",
    receiptPersonId: "USR123456789",
    checkNumber: "CHK987654",
    checkSecurityCode: "456",
    checkAmount: 1500,
    checkHolderName: "Jane Smith",
    paymentDay: "2024-04-20",
    status: "Processed",
  },
  {
    no: 3,
    paymentId: "PAY456789123",
    projectName: "Project C",
    countryName: "UK",
    receiptPersonId: "USR789123456",
    checkNumber: "CHK456789",
    checkSecurityCode: "789",
    checkAmount: 2000,
    checkHolderName: "Michael Johnson",
    paymentDay: "2024-04-21",
    status: "Completed",
  },
  {
    no: 4,
    paymentId: "PAY456789456",
    projectName: "Project D",
    countryName: "Australia",
    receiptPersonId: "USR456789123",
    checkNumber: "CHK789123",
    checkSecurityCode: "012",
    checkAmount: 2500,
    checkHolderName: "Emily Brown",
    paymentDay: "2024-04-22",
    status: "Pending",
  },
  {
    no: 5,
    paymentId: "PAY789123456",
    projectName: "Project E",
    countryName: "Germany",
    receiptPersonId: "USR654321987",
    checkNumber: "CHK321987",
    checkSecurityCode: "345",
    checkAmount: 3000,
    checkHolderName: "William Davis",
    paymentDay: "2024-04-23",
    status: "Processed",
  },
];

export const RefundData: IRefundPayment[] = [
  {
    no: 1,
    refundId: "REF001",
    projectName: "Project A",
    refundMethod: "Bank Transfer",
    accountName: "John Doe",
    accountNumber: "123456789",
    refundAmount: 500,
    refundDay: "2024-04-19",
    status: "Success",
  },
  {
    no: 2,
    refundId: "REF002",
    projectName: "Project B",
    refundMethod: "Credit Card",
    accountName: "Jane Smith",
    accountNumber: "**** **** **** 5678",
    refundAmount: 800,
    refundDay: "2024-04-20",
    status: "Pending",
  },
  {
    no: 3,
    refundId: "REF003",
    projectName: "Project C",
    refundMethod: "PayPal",
    accountName: "Michael Johnson",
    accountNumber: "michael.johnson@example.com",
    refundAmount: 1000,
    refundDay: "2024-04-21",
    status: "Success",
  },
  {
    no: 4,
    refundId: "REF004",
    projectName: "Project D",
    refundMethod: "Bank Transfer",
    accountName: "Emily Brown",
    accountNumber: "987654321",
    refundAmount: 700,
    refundDay: "2024-04-22",
    status: "Pending",
  },
  {
    no: 5,
    refundId: "REF005",
    projectName: "Project E",
    refundMethod: "Credit Card",
    accountName: "Daniel Wilson",
    accountNumber: "**** **** **** 9012",
    refundAmount: 600,
    refundDay: "2024-04-23",
    status: "Success",
  },
  {
    no: 6,
    refundId: "REF006",
    projectName: "Project F",
    refundMethod: "Bank Transfer",
    accountName: "Olivia Taylor",
    accountNumber: "123987456",
    refundAmount: 900,
    refundDay: "2024-04-24",
    status: "Success",
  },
  {
    no: 7,
    refundId: "REF007",
    projectName: "Project G",
    refundMethod: "PayPal",
    accountName: "Sophia Martinez",
    accountNumber: "sophia.martinez@example.com",
    refundAmount: 1200,
    refundDay: "2024-04-25",
    status: "Pending",
  },
];
